#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */


require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/application/config/_constants.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require APPLICATION_DIR.'/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
